---
---
apiVersion: v1
kind: Secret
metadata:
  name: simple
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: kubernetes.io/basic-auth
stringData:
  username: <USER_ACCESS_KEY>
  password: sn0rt_<USER_SECRET_KEY>
  host: localhost.local
