apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.env.frontend.PORT }}
      targetPort: {{ .Values.env.frontend.PORT | default "3000" }}
      name: frontend
    - port: {{ .Values.env.backend.PORT }}
      targetPort: {{ .Values.env.backend.PORT | default "3001" }}
      name: backend
  selector:
    app: secret2es
