apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: tenant-b
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
      path: secret
      server: http://vault:8200
      version: v2
---
apiVersion: v1
data:
  token: cm9vdA==
kind: Secret
metadata:
  name: vault-token
type: Opaque