apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: tenant-approle1
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: {ROLE_ID}
          secretRef:
            key: AVP_SECRET_ID
            name: vault-cred-tenant
            namespace: default
      path: secret
      server: http://vault:8200
      version: v2
---
apiVersion: v1
data:
  AVP_SECRET_ID: {SECRET_ID}
kind: Secret
metadata:
  name: vault-cred-tenant
  namespace: default
type: Opaque