---
---
apiVersion: v1
kind: Secret
metadata:
  name: input0
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: kubernetes.io/basic-auth
stringData:
  host: "localhost.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: input1
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: kubernetes.io/basic-auth
stringData:
  username: <TEST_USERNAME>
  password: <TEST_PASSWORD>
  host: "localhost.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: input2
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: Opaque
data:
  dist: <TEST_DIST_LINUX> #version
---
apiVersion: v1
kind: Secret
metadata:
  name: input3
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: Opaque
data:
  dist: <TEST_DIST_LINUX> #DIST_OF_NAME_LINUX
---
apiVersion: v1
kind: Secret
metadata:
  name: input4
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: Opaque
data:
  dist: <TEST_DIST_LINUX> #DIST_OF_NAME_LINUX
  user: <TEST_USERNAME> #USER_NAME_OF_GITHUB
  password: <TEST_PASSWORD>
  host: "localhost.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: input5
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: Opaque
stringData:
  mylogin.conf: |
    [client]
    host = example.com
    user = <MYSQL_USER>
    password = <MYSQL_PASSWD>
    port = 4000
---
# skip this one
apiVersion: v1
kind: Secret
metadata:
  name: input6
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: Opaque
stringData:
  sn0rt.github.io.default.access_key: "VVNFUl9BQ0NFU1NfS0VZCg==" #USER_ACCESS_KEY
  sn0rt.github.io.default.secret_key: "VVNFUl9TRUNSRVRfS0VZCg==" #USER_SECRET_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: input6
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: Opaque
stringData:
  sn0rt.github.io.default.access_key: <ACCESS_KEY> #USER_ACCESS_KEY
  sn0rt.github.io.default.secret_key: <SECRET_KEY> #USER_SECRET_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: input7
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: kubernetes.io/tls
data:
  tls.crt: <TLS_CRT>
  tls.key: <TLS_KEY>
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: input7
#  annotations:
#    avp.kubernetes.io/path: "secret/data/test-foo"
#type: kubernetes.io/tls
#data:
#  tls.crt: <TLS_CRT>
#  tls.key: <TLS_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: input8
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1": {
          "auth": "<TEST_PASSWORD>"
        },
        "https://index.docker.io:8443/v1": {
          "auth": "<TEST_PASSWORD>"
        }      
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: input9
  annotations:
    avp.kubernetes.io/path: "secret/data/test-foo"
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyakNDQVpZQ0NRQ1N4TjdEbUl3OVRqQU5CZ2txaGtpRzl3MEJBUXNGQURBWk1SY3dGUVlEVlFRRERBNTUKYjNWeVpHOXRZV2x1TG1OdmJUQWVGdzB5TkRBNE1qWXdOakV4TlRKYUZ3MHlOVEE0TWpZd05qRXhOVEphTUJreApGekFWQmdOVkJBTU1Ebmx2ZFhKa2IyMWhhVzR1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXpJZDZDMU12ZkN3V0xDanNnejEwa29Ga3M2RklIbHlVNElwUDVtcitERVRGTnFKT1p6dnoKZStreGFFNjBsYkNhVDV6U2YxZDllQWM0M0t2b0w1eXBieUxWVGJjdCtlNnNYMm9rbWlzdGtxUmRxcjNtMm9hSAoyY3pKeUhEVVpyT3Z6SkRHTDJoNGdUdE03QXpsb3VaN3ViOGZNQUJDR3B5bUppNjlzMEZRQ21DakltWUdxcm02CnlpOU83VXp4bTlabmgzUWhXZ2xzbFJuS05oVUhzdHIxbnQ0K1NsMWU2TEhBbHJtTzF5eVJHUmphdHh1d1NKYTMKTUZKeFJnTHRWbnlMNzJmTWY3c1R3RzcrbDVXMmhsM2x5QW1yeGpORnIvMGJ6WHBVZHFnc0dObW84Ny80NmdSego1UFMrZVc5UzNwVDZPN2NkUlQzcTB3NVk2VUhidGdIQ3d3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQU1HS3paS2ZsTllwRkpDczNMMEt6TFgrWmEzdG9jQUlBODFjQXU0NzNEem9uc1B3cEZaUnRPeVAzV0Foc0EKalpNcitnaVhkY3lvWjVEQTdEUkkxN0UxSDduZTFiaDR6RmtYRE1HdGQxdnZXM0xQNVlhb2NxUjlzdGMyL3A0dgpxVE03bjZ0alRqY2RYNEQ2eG5KSHRzbmF1dVBwTUdiTzUwK04yK3JobU1NbjZPVmpFRkgrRWlQYmYzNWtSbkhXCi83ZnowWnVtYkxwNUlqdWFjSFM2YXJwR25KNGZON1I2NVNHa0FpNEtvMFZ6VTNNM1laclFneFdpK29aTHpTUHUKUUZveWpYRlgvQlhBRG9vaEFuTlpkN2FmVmFaMlU3MjJqaEpKaEkxM0tobHRXb2RUT2hQVytabWxYeHZmRy9acwprdU1SVmZraHowaGlQWGtMWUVvQTZlN3MKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  tls.key: <TLS_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: approle1-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/approle1-secret"
type: kubernetes.io/basic-auth
stringData:
  username: <MYSQL_USER>
  password: <MYSQL_PASSWORD>
