image:
  repository: wangguohao/secret2es
  tag: dev

replicaCount: 1

namespace: default

env:
  frontend:
    PORT: 3000
    HOSTNAME: "0.0.0.0"
  backend:
    PORT: 3001

ingress:
  enabled: true
  host: localhost
