name: Release

on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_REPO: wangguohao
  IMAGE_NAME: secret2es

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set build time
        run: echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build Docker image
        run: |
          docker build \
          --build-arg VERSION=${{ steps.meta.outputs.version }} \
          --build-arg BUILD_TIME=${{ env.BUILD_TIME }} \
          -t ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} \
          -t ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest \
          .

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          docker push ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest          

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'